In [13]:
import numpy as np
#1
a = np.array([[0, 2, -1],
             [-2, -1, 2],
             [3, -2, -1]])

b = np.array([[70, 34, -107],
             [52, 26, -68],
             [101, 50, -140]])

sum = a + b
sum

array([[  70,   36, -108],
       [  50,   25,  -66],
       [ 104,   48, -141]])

In [16]:
#2
c = np.array([[2, -1, 1],
             [3, 0, 1]])

d = np.array([[1, 1, -2],
             [0, 1, 2],
             [-1, 0, 1]])

product = np.dot(c, d)
product

array([[ 1,  1, -5],
       [ 2,  3, -5]])

In [43]:
#3
e = np.array([[3, 1, -1, 5, 2]])

f = np.array([[4, 0, -2, 3, 1]])

product_ef = np.dot(e.T, f)
product_ef

array([[ 12,   0,  -6,   9,   3],
       [  4,   0,  -2,   3,   1],
       [ -4,   0,   2,  -3,  -1],
       [ 20,   0, -10,  15,   5],
       [  8,   0,  -4,   6,   2]])

In [22]:
#4
g = np.array([[-11, 31, 1, -5],
             [6, -2, 3, -1],
             [1, 0, 5, -2],
             [1, -4, 8, 7]])
trans = g.T
trans

array([[-11,   6,   1,   1],
       [ 31,  -2,   0,  -4],
       [  1,   3,   5,   8],
       [ -5,  -1,  -2,   7]])

In [369]:
#5
matrix = np.array([[3, -5, 4],
             [5, 2, 1],
             [2, 3, -2]])

matrix_1 = np.array([5, 0, 3])
m = np.linalg.det(matrix)

X = np.linalg.solve(matrix, matrix_1)
print(X)
print(m)

[ 2. -3. -4.]
-37.0


In [375]:
#6
matrix6 = np.array([[3, 1, 7],
             [5, 3, 9],
             [2, 1, 4]])

ans = np.array([7, 13, 5])

matrix61 = np.array([[7, 13, 5],
             [5, 3, 9],
             [2, 1, 4]])

matrix62 = np.array([[3, 1, 7],
             [7, 13, 5],
             [2, 1, 4]])

matrix63 = np.array([[3, 1, 7],
             [5, 3, 9],
             [7, 13, 5]])


det = np.linalg.det(new_matrix)
det1 = np.linalg.det(matrix61)
det2 = np.linalg.det(matrix62)
det3 = np.linalg.det(matrix63)

ans1 = det1/det
ans2 = det2/det
ans3 = det3/det

print('determinants:', [det, det1, det2, det3])
print('answers:', [ans1, ans2, ans3])

determinants: [-4.440892098500646e-16, -10.000000000000002, -9.999999999999984, 40.0]
answers: [2.2517998136852384e+16, 2.2517998136852344e+16, -9.007199254740952e+16]


In [360]:
#8
g = np.array([[2, 3, 7, 11],
             [1, 2, 4, 7],
             [5, 0, 10, 5]])
rank_g = np.linalg.matrix_rank(g)
rank_g

2

In [362]:
#9

h = np.array([[2, 1, 3, 0],
             [1, 4, 2, 1],
             [3, 2, 2, 6],
             [8, 5, 7, 12]])
rank_h = np.linalg.matrix_rank(h)
rank

2

In [ ]:
Y_1 = [[50],
    [60],
    [55],
    [75],
    [48],
    [65],
    [72],
    [52],
    [80],
    [58],
    [70],
    [45],
    [90],
    [53],
    [62],
    [48],
    [85],
    [55],
    [75],
    [43]]

In [16]:
#10 Y = coef1*x1 + coef2*x2 + coef3*x3 + coef4*x4 + coef5*x5

Y = [50,
    60,
    55,
    75,
    48,
    65,
    72,
    52,
    80,
    58,
    70,
    45,
    90,
    53,
    62,
    48,
    85,
    55,
    75,
    43]
X = [[12, 175, 70, 0, 1],
    [16, 180, 75, 0, 1],
    [14, 165, 60, 1, 1],
    [18, 185, 80, 0, 1],
    [12, 170, 68, 0, 1],
    [15, 175, 72, 1, 1],
    [17, 178, 76, 0, 1],
    [13, 162, 65, 1, 1],
    [20, 190, 85, 0, 1],
    [14, 168, 70, 1, 1],
    [16, 177, 74, 0, 1],
    [10, 160, 58, 1, 1],
    [22, 192, 88, 0, 1],
    [13, 171, 69, 1, 1],
    [15, 173, 71, 0, 1],
    [11, 166, 67, 1, 1],
    [19, 188, 82, 0, 1],
    [14, 169, 70, 1, 1],
    [17, 176, 75, 0, 1],
    [10, 162, 57, 1, 1]]

Y = np.array(Y)
X = np.array(X)

x1 = X[:, 0]
x2 = X[:, 1]
x3 = X[:, 2]
x4 = X[:, 3]
x5 = X[:, 4]



NameError: name 'np' is not defined

In [351]:
def simple_ols(X, Y):
  X_transpose = X.T
  X_transpose_X = X_transpose @ X
  if np.linalg.det(X_transpose_X) != 0:
    X_t_X_inv = np.linalg.inv(X_transpose_X)
  else:
    print('Error')
  X_t_X_inv_X_t = X_t_X_inv @ X_transpose
  coefs = X_t_X_inv_X_t @ Y
  return coefs

def find_mse(Y_actual, Y_predicted):
    squares = []
    error = Y_actual - Y_predicted
    squares =[i**2 for i in error]
    summa = 0
    for j in squares:
        summa+=j
    mse = summa/len(Y_actual)
    return mse

coef = simple_ols(X, Y)
Y_predicted = x1* coef[0] + x2* coef[1] + x3 * coef[2] + x4 * coef[3] + x5*coef[4]
mse = find_mse(Y, Y_predicted)

print('Coefs and MSE:', coef, round(mse, 5))

Coefs and MSE: [ 3.94749408  0.02729828  0.02746017 -0.33853817 -3.33409793] 8.83817


In [337]:
from sklearn.metrics import mean_squared_error
mse1 = mean_squared_error(Y, Y_predicted)
round(mse1, 5)

8.83817

In [ ]:
Y = [50,
    60,
    55,
    75,
    48,
    65,
    72,
    52,
    80,
    58,
    70,
    45,
    90,
    53,
    62,
    48,
    85,
    55,
    75,
    43]
X = [[12, 175, 70, 0, 1],
    [16, 180, 75, 0, 1],
    [14, 165, 60, 1, 1],
    [18, 185, 80, 0, 1],
    [12, 170, 68, 0, 1],
    [15, 175, 72, 1, 1],
    [17, 178, 76, 0, 1],
    [13, 162, 65, 1, 1],
    [20, 190, 85, 0, 1],
    [14, 168, 70, 1, 1],
    [16, 177, 74, 0, 1],
    [10, 160, 58, 1, 1],
    [22, 192, 88, 0, 1],
    [13, 171, 69, 1, 1],
    [15, 173, 71, 0, 1],
    [11, 166, 67, 1, 1],
    [19, 188, 82, 0, 1],
    [14, 169, 70, 1, 1],
    [17, 176, 75, 0, 1],
    [10, 162, 57, 1, 1]]

Y = np.array(Y)
X = np.array(X)
x1 = X[:, 0]
x2 = X[:, 1]
x3 = X[:, 2]
x4 = X[:, 3]
x5 = X[:, 4]

def simple_ols(X, Y):
  X_transpose = X.T
  X_transpose_X = X_transpose @ X
  if np.linalg.det(X_transpose_X) != 0:
    X_t_X_inv = np.linalg.inv(X_transpose_X)
  else:
    print('Error')
  X_t_X_inv_X_t = X_t_X_inv @ X_transpose
  coefs = X_t_X_inv_X_t @ Y
  return coefs

def find_mse(Y_actual, Y_predicted):
    squares = []
    error = Y_actual - Y_predicted
    squares =[i**2 for i in error]
    summa = 0
    for j in squares:
        summa+=j
    mse = summa/len(Y_actual)
    return mse

coef = simple_ols(X, Y)
Y_predicted = x1* coef[0] + x2* coef[1] + x3 * coef[2] + x4 * coef[3] + x5*coef[4]
mse = find_mse(Y, Y_predicted)

print('Coefs and MSE:', coef, round(mse, 5))

#alternative for mse
from sklearn.metrics import mean_squared_error
mse1 = mean_squared_error(Y, Y_predicted)
print('Coefs and MSE:', coef, round(mse1, 5))

[[ 3.94749408  0.02729828  0.02746017 -0.33853817 -3.33409793], 8.83817]